# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model360ti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=2000)),
                ('loc', models.CharField(max_length=100)),
            ],
        ),
    ]
